<div id="cabecera" style="width:1000px; height:60px;">
<a href="http://www.icityproject.com/">
<img src="images/icity_logo.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/Termometro.png" height="50" border="0">
<img src="images/BCN.jpg" height="50" border="0" valign="right">
<img src="images/Smart_Citizen.png" height="50" border="0" valign="right">
</a>
</div>
<div style="clear:left;"></div>